import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

type RemotePattern = {
  protocol: "http" | "https";
  hostname: string;
  port?: string;
  pathname: string;
};

/**
 * Parse a host or absolute origin into a next/image remotePattern.
 * Accepts `cdn.example.com`, `https://cdn.example.com/`, trailing slashes.
 *
 * @param keepPath — when true, a non-root pathname becomes a prefix
 *   (`https://cdn.example.com/media/` → `/media/**`). API origins should
 *   pass false so `/api` does not block `/storage/...` media on the same host.
 */
function patternFromHost(
  raw: string,
  keepPath = false,
): RemotePattern | undefined {
  const value = raw.trim();
  if (!value) return undefined;

  try {
    const url = value.includes("://")
      ? new URL(value)
      : new URL(`https://${value}`);

    const protocol = url.protocol === "http:" ? "http" : "https";
    const hostname = url.hostname;
    if (!hostname) return undefined;

    let pathname = "/**";
    if (keepPath) {
      const basePath = url.pathname.replace(/\/+$/, "");
      if (basePath && basePath !== "/") pathname = `${basePath}/**`;
    }

    const pattern: RemotePattern = { protocol, hostname, pathname };
    if (url.port) pattern.port = url.port;
    return pattern;
  } catch {
    return undefined;
  }
}

/**
 * Allow next/image to optimize remote CMS/CDN URLs.
 *
 * `hostname: "**"` is evaluated at build and permits any https/http host at
 * runtime (API, Unsplash, MEDIA_HOST) without rebuilding when the CDN changes.
 * Specific hosts from env are still added when present (narrower patterns).
 */
function buildRemotePatterns(): RemotePattern[] {
  const patterns: RemotePattern[] = [
    { protocol: "https", hostname: "**", pathname: "/**" },
    { protocol: "http", hostname: "**", pathname: "/**" },
  ];
  const seen = new Set(
    patterns.map(
      (p) => `${p.protocol}://${p.hostname}:${p.port ?? ""}${p.pathname}`,
    ),
  );

  const add = (raw: string | undefined, keepPath = false) => {
    if (!raw) return;
    const pattern = patternFromHost(raw, keepPath);
    if (!pattern) return;
    const key = `${pattern.protocol}://${pattern.hostname}:${pattern.port ?? ""}${pattern.pathname}`;
    if (seen.has(key)) return;
    seen.add(key);
    patterns.push(pattern);
  };

  add(process.env.API_URL ?? process.env.NEXT_PUBLIC_API_URL, false);
  add(process.env.MEDIA_HOST ?? process.env.NEXT_PUBLIC_MEDIA_HOST, true);

  return patterns;
}

const nextConfig: NextConfig = {
  output: "standalone",
  /**
   * Slack/WhatsApp prefer an image URL that ends in `.png`/`.jpg`. The brand
   * card is generated by `app/opengraph-image.tsx`; expose it as `/og.png`.
   */
  async rewrites() {
    return [{ source: "/og.png", destination: "/opengraph-image" }];
  },
  images: {
    formats: ["image/avif", "image/webp"],
    /** Prefer AVIF/WebP; slightly tighter device list for faster LCP variants. */
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    remotePatterns: buildRemotePatterns(),
  },
};

const withNextIntl = createNextIntlPlugin();

export default withNextIntl(nextConfig);
